name: 🧪 Lint & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  changes:
    name: 🎯 identify changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read

    outputs:
      go: ${{ steps.filter.outputs.go }}
      pnpm: ${{ steps.filter.outputs.pnpm }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: dorny/paths-filter@v4.0.1
        id: filter
        with:
          filters: |
            go:
              - backend/**
            pnpm:
              - frontend/web/**
              - '**/*.yaml'
              - '**/*.json'
              - '**/*.md'
            frontend:
              - frontend/web/**

  format-pnpm:
    name: 🎨 format (pnpm)
    needs: changes
    if: ${{ needs.changes.outputs.pnpm == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm check

  check-frontend-web:
    name: 📋 check frontend/web (pnpm)
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      - name: Check frontend/web
        working-directory: ./frontend/web
        run: pnpm check

      - name: Build frontend/web
        working-directory: ./frontend/web
        run: pnpm build

  test-lint-backend:
    name: 🧪 test & lint backend (go)
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Install backend dependencies
        working-directory: ./backend
        run: make all

      - name: Test & build backend
        working-directory: ./backend
        run: |
          make test
          make test-build

      - name: Lint backend
        working-directory: ./backend
        run: make lint
