name: 🚀 Publish & Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Create image tag
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker build --pull -t ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} -t ghcr.io/${{ github.repository }}:latest --build-arg VERSION="${{ github.ref_name }}" .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Fetch image and compose up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/app
            curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yaml
            docker compose pull
            docker compose up -d
            docker image prune -a -f
