name: Deploy Adnexos

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Docker image tag, e.g. `1.0.0`
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t tametsi/adnexos:${{ inputs.tag }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push tametsi/adnexos:${{ inputs.tag }}

      - name: Fetch image and compose up
        uses: appleboy/ssh-action@v1
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          envs: IMAGE_TAG
          script: |
            cd ~/app
            docker compose up -d
            docker image prune -a
