name: Build & Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Create image tag
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ${{ github.repository }}:${{ env.IMAGE_TAG }} --build-arg VERSION="${{ github.ref_name }}" .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push ${{ github.repository }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create image tag
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - name: Fetch image and compose up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          envs: IMAGE_TAG
          script: |
            cd ~/app
            docker compose up -d
            docker image prune -a
